package lab1tp6;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonel
 */
public class BusquedaPrecioIFrame extends javax.swing.JInternalFrame implements Observador {

    private final DefaultTableModel dtm;
    private final ListaProductos listaProductos;

    /**
     * Creates new form BusquedaPrecioIFrame
     *
     * @param listaProductos
     */
    public BusquedaPrecioIFrame(ListaProductos listaProductos) {
        initComponents();
        this.listaProductos = listaProductos;
        dtm = (DefaultTableModel) jdTablaBusquedaPrecio.getModel();
        actualizarBusquedaPrecio();
    }

    private void actualizarBusquedaPrecio() {
        String limInfStr = (String) tfBusquedaPrecioLimInf.getText();
        String limSupStr = (String) tfBusquedaPrecioLimSup.getText();
        double limiteInferior, limiteSuperior;
        if (limInfStr.isBlank() || limSupStr.isBlank()) {
            return;
        }
        try {
            limiteInferior = Double.parseDouble(limInfStr);
            limiteSuperior = Double.parseDouble(limSupStr);
        } catch (NumberFormatException e) {
            // No hay problema, simplemente salimos
            return;
        }
        dtm.setRowCount(0);
        for (Producto producto : listaProductos.getProductos()) {
            double precio = producto.getPrecio();
            if (precio >= limiteInferior && precio <= limiteSuperior) {
                dtm.addRow(new Object[]{producto.getCodigo(), producto.getDescripcion(), producto.getPrecio(), producto.getExistencias()});
            }
        }
    }

    @Override
    public void actualizar() {
        actualizarBusquedaPrecio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        lPrecioLimInf = new javax.swing.JLabel();
        javax.swing.JLabel lPrecioLimSup = new javax.swing.JLabel();
        tfBusquedaPrecioLimInf = new javax.swing.JTextField();
        tfBusquedaPrecioLimSup = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jdTablaBusquedaPrecio = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Búsqueda por Precio");

        lTitulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Listado de Productos por Precio");

        lPrecioLimInf.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lPrecioLimInf.setText("Entre $:");

        lPrecioLimSup.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lPrecioLimSup.setText("y");

        tfBusquedaPrecioLimInf.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfBusquedaPrecioLimInf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBusquedaPrecioLimInfKeyReleased(evt);
            }
        });

        tfBusquedaPrecioLimSup.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfBusquedaPrecioLimSup.setName(""); // NOI18N
        tfBusquedaPrecioLimSup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBusquedaPrecioLimSupKeyReleased(evt);
            }
        });

        jdTablaBusquedaPrecio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jdTablaBusquedaPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jdTablaBusquedaPrecio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lPrecioLimInf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfBusquedaPrecioLimInf, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lPrecioLimSup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfBusquedaPrecioLimSup, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBusquedaPrecioLimInf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPrecioLimSup)
                    .addComponent(tfBusquedaPrecioLimSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPrecioLimInf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBusquedaPrecioLimInfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBusquedaPrecioLimInfKeyReleased
        actualizarBusquedaPrecio();
    }//GEN-LAST:event_tfBusquedaPrecioLimInfKeyReleased

    private void tfBusquedaPrecioLimSupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBusquedaPrecioLimSupKeyReleased
        actualizarBusquedaPrecio();
    }//GEN-LAST:event_tfBusquedaPrecioLimSupKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jdTablaBusquedaPrecio;
    private javax.swing.JLabel lPrecioLimInf;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextField tfBusquedaPrecioLimInf;
    private javax.swing.JTextField tfBusquedaPrecioLimSup;
    // End of variables declaration//GEN-END:variables
}
