package lab1tp6;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonel
 */
public class BusquedaNombreIFrame extends javax.swing.JInternalFrame implements Observador {

    private final DefaultTableModel dtm;
    private final ListaProductos listaProductos;

    /**
     * Creates new form BusquedaNombreIFrame
     *
     * @param listaProductos
     */
    public BusquedaNombreIFrame(ListaProductos listaProductos) {
        initComponents();
        this.listaProductos = listaProductos;
        dtm = (DefaultTableModel) jdTablaBusquedaNombre.getModel();
        actualizarBusquedaNombre();
    }

    private void actualizarBusquedaNombre() {
        String nombre = (String) tfBusquedaNombre.getText().toLowerCase();
        int nombreLongitud = nombre.length();
        dtm.setRowCount(0);
        if (nombreLongitud == 0) {
            return;
        }

        for (Producto producto : listaProductos.getProductos()) {
            int longitud = producto.getDescripcion().length();
            longitud = nombreLongitud > longitud ? longitud : nombreLongitud;
            if (producto.getDescripcion().substring(0, longitud).toLowerCase().equals(nombre)) {
                dtm.addRow(new Object[]{producto.getCodigo(), producto.getDescripcion(), producto.getPrecio(), producto.getExistencias()});
            }
        }
    }

    @Override
    public void actualizar() {
        actualizarBusquedaNombre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        lElegirNombre = new javax.swing.JLabel();
        tfBusquedaNombre = new javax.swing.JTextField();
        spTabla = new javax.swing.JScrollPane();
        jdTablaBusquedaNombre = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Búsqueda por Nombre");

        lTitulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Listado de Productos por Nombre");

        lElegirNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lElegirNombre.setText("Escriba los primeros caracteres");

        tfBusquedaNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfBusquedaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBusquedaNombreKeyReleased(evt);
            }
        });

        jdTablaBusquedaNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jdTablaBusquedaNombre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTabla.setViewportView(jdTablaBusquedaNombre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lElegirNombre)
                        .addGap(18, 18, 18)
                        .addComponent(tfBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lElegirNombre)
                    .addComponent(tfBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(spTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBusquedaNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBusquedaNombreKeyReleased
        actualizarBusquedaNombre();
    }//GEN-LAST:event_tfBusquedaNombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jdTablaBusquedaNombre;
    private javax.swing.JLabel lElegirNombre;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JScrollPane spTabla;
    private javax.swing.JTextField tfBusquedaNombre;
    // End of variables declaration//GEN-END:variables

}
