package lab1tp6;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonel
 */
public class BusquedaRubroIFrame extends javax.swing.JInternalFrame implements Observador {

    private final DefaultTableModel dtm;
    private final ListaProductos listaProductos;

    /**
     * Creates new form BusquedaRubroIFrame
     *
     * @param listaProductos
     */
    public BusquedaRubroIFrame(ListaProductos listaProductos) {
        initComponents();
        this.listaProductos = listaProductos;
        dtm = (DefaultTableModel) jdTablaBusquedaRubro.getModel();
        actualizarBusquedaRubro();
    }

    private void actualizarBusquedaRubro() {
        String rubro = (String) cbElegirRubro.getSelectedItem();
        if (rubro == null) {
            return;
        }
        dtm.setRowCount(0);
        for (Producto producto : listaProductos.getProductos()) {
            if (producto.getRubro().equals(rubro)) {
                dtm.addRow(new Object[]{producto.getCodigo(), producto.getDescripcion(), producto.getPrecio(), producto.getExistencias()});
            }
        }
    }

    @Override
    public void actualizar() {
        actualizarBusquedaRubro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        lElegirRubro = new javax.swing.JLabel();
        cbElegirRubro = new javax.swing.JComboBox<>();
        spTabla = new javax.swing.JScrollPane();
        jdTablaBusquedaRubro = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Búsqueda por Rubro");
        setName(""); // NOI18N

        lTitulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Listado de Productos por Rubro");

        lElegirRubro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lElegirRubro.setText("Elija rubro:");

        cbElegirRubro.setModel(new DefaultComboBoxModel(Rubro.capitalized()));
        cbElegirRubro.setSelectedIndex(-1);
        cbElegirRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbElegirRubroActionPerformed(evt);
            }
        });

        jdTablaBusquedaRubro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jdTablaBusquedaRubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTabla.setViewportView(jdTablaBusquedaRubro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lElegirRubro)
                .addGap(18, 18, 18)
                .addComponent(cbElegirRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lElegirRubro)
                    .addComponent(cbElegirRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(spTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbElegirRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbElegirRubroActionPerformed
        actualizarBusquedaRubro();
    }//GEN-LAST:event_cbElegirRubroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbElegirRubro;
    private javax.swing.JTable jdTablaBusquedaRubro;
    private javax.swing.JLabel lElegirRubro;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JScrollPane spTabla;
    // End of variables declaration//GEN-END:variables
}
