package lab1tp6;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Leonel
 */
public class GestorFrame extends javax.swing.JFrame {

    private final ListaProductos productos;
    ProductoIFrame productoIFrame;
    BusquedaRubroIFrame busquedaRubroIFrame;
    BusquedaNombreIFrame busquedaNombreIFrame;
    BusquedaPrecioIFrame busquedaPrecioIFrame;

    /**
     * Creates new form GestorFrame
     */
    public GestorFrame() {
        initComponents();
        productos = new ListaProductos();
        
        productoIFrame = new ProductoIFrame(productos);
        jDesktopPane1.add(productoIFrame);
        
        busquedaRubroIFrame = new BusquedaRubroIFrame(productos);
        jDesktopPane1.add(busquedaRubroIFrame);
        productos.agregarObservador(busquedaRubroIFrame);
        
        busquedaNombreIFrame = new BusquedaNombreIFrame(productos);
        jDesktopPane1.add(busquedaNombreIFrame);
        productos.agregarObservador(busquedaNombreIFrame);
        
        busquedaPrecioIFrame = new BusquedaPrecioIFrame(productos);
        jDesktopPane1.add(busquedaPrecioIFrame);
        productos.agregarObservador(busquedaPrecioIFrame);
        /* Data para trabajar */
        productos.agregar(new Producto(1000, "Galletas", 12.20, 10, "Comestible"));
        productos.agregar(new Producto(1001, "Arroz", 8.75, 9, "Comestible"));
        productos.agregar(new Producto(2000, "Jabón", 4.85, 20, "Limpieza"));
        productos.agregar(new Producto(2001, "Lejía", 6.90, 7, "Limpieza"));
        productos.agregar(new Producto(3000, "Perfume A", 29.99, 6, "Perfumeria"));
        productos.agregar(new Producto(3001, "Perfume B", 34.99, 5, "Perfumeria"));
    }

    private void focusIFrame(JInternalFrame iFrame) {
        boolean iconified = false;
        try {
            iconified = iFrame.isIcon();
            iFrame.setIcon(false);
            iFrame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GestorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!iFrame.isVisible() || iconified) {
            iFrame.setLocation(0, 0);
            iFrame.setVisible(true);
        }
        iFrame.moveToFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdministracion = new javax.swing.JMenu();
        jmiProductos = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmiPorRubro = new javax.swing.JMenuItem();
        jmiPorNombre = new javax.swing.JMenuItem();
        jmiPorPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Productos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("gestorFrame"); // NOI18N

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(640, 457));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jmAdministracion.setText("Administración");
        jmAdministracion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jmiProductos.setText("Productos");
        jmiProductos.setToolTipText("");
        jmiProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductosActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmiProductos);

        jMenuBar1.add(jmAdministracion);

        jmConsultas.setText("Consultas");
        jmConsultas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jmiPorRubro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jmiPorRubro.setText("Por Rubro");
        jmiPorRubro.setToolTipText("");
        jmiPorRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPorRubroActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiPorRubro);

        jmiPorNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jmiPorNombre.setText("Por Nombre");
        jmiPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPorNombreActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiPorNombre);

        jmiPorPrecio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jmiPorPrecio.setText("Por Precio");
        jmiPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPorPrecioActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiPorPrecio);

        jMenuBar1.add(jmConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductosActionPerformed
        focusIFrame(productoIFrame);
    }//GEN-LAST:event_jmiProductosActionPerformed

    private void jmiPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPorRubroActionPerformed
        focusIFrame(busquedaRubroIFrame);
    }//GEN-LAST:event_jmiPorRubroActionPerformed

    private void jmiPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPorNombreActionPerformed
        focusIFrame(busquedaNombreIFrame);
    }//GEN-LAST:event_jmiPorNombreActionPerformed

    private void jmiPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPorPrecioActionPerformed
        focusIFrame(busquedaPrecioIFrame);
    }//GEN-LAST:event_jmiPorPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void ejecutar(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenuItem jmiPorNombre;
    private javax.swing.JMenuItem jmiPorPrecio;
    private javax.swing.JMenuItem jmiPorRubro;
    private javax.swing.JMenuItem jmiProductos;
    // End of variables declaration//GEN-END:variables
}
