package lab1tp6;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonel
 */
public class ProductoIFrame extends javax.swing.JInternalFrame {

    private final ListaProductos listaProductos;

    /**
     * Creates new form NewJInternalFrame
     * @param listaProductos
     */
    public ProductoIFrame(ListaProductos listaProductos) {
        initComponents();
        this.listaProductos = listaProductos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        bBuscar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        bNuevo = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        lCodigo = new javax.swing.JLabel();
        lDescripcion = new javax.swing.JLabel();
        lPrecio = new javax.swing.JLabel();
        lRubro = new javax.swing.JLabel();
        lStock = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfDescripcion = new javax.swing.JTextField();
        tfPrecio = new javax.swing.JTextField();
        cbRubro = new javax.swing.JComboBox<>();
        tfExistencias = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Gestión de Productos");

        lTitulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Gestión de Productos");

        bBuscar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa16.png"))); // NOI18N
        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bEliminar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bGuardar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bNuevo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bNuevo.setText("Limpiar");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });

        bSalir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        lCodigo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lCodigo.setText("Código");

        lDescripcion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lDescripcion.setText("Descripción");

        lPrecio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lPrecio.setText("Precio");

        lRubro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lRubro.setText("Rubro");

        lStock.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lStock.setText("Stock");

        tfCodigo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfCodigo.setToolTipText("");

        tfDescripcion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        tfPrecio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        cbRubro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbRubro.setModel(new DefaultComboBoxModel(Rubro.capitalized()));
        cbRubro.setSelectedIndex(-1);

        tfExistencias.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lDescripcion)
                                    .addComponent(lCodigo)
                                    .addComponent(lPrecio))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(tfCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPrecio)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lRubro)
                                    .addComponent(lStock))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfExistencias)
                                    .addComponent(cbRubro, 0, 150, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(bGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(bEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(bSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lCodigo)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDescripcion)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrecio)
                    .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRubro)
                    .addComponent(cbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStock)
                    .addComponent(tfExistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNuevo)
                    .addComponent(bGuardar)
                    .addComponent(bEliminar)
                    .addComponent(bSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        int codigo;
        try {
            codigo = Integer.parseInt(tfCodigo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Se esperaba un numero entero en Código", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Producto p = null;
        for (Producto producto : listaProductos.getProductos()) {
            if (producto.getCodigo() == codigo) {
                p = producto;
            }
        }
        if (p != null) {
            tfDescripcion.setText(p.getDescripcion());
            tfPrecio.setText(String.valueOf(p.getPrecio()));
            cbRubro.setSelectedItem(p.getRubro());
            tfExistencias.setText(String.valueOf(p.getExistencias()));
        } else {
            tfDescripcion.setText("");
            tfPrecio.setText("");
            tfExistencias.setText("");
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed
        tfCodigo.setText("");
        tfDescripcion.setText("");
        tfPrecio.setText("");
        cbRubro.setSelectedIndex(-1);
        tfExistencias.setText("");
    }//GEN-LAST:event_bNuevoActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        int codigo;
        try {
            codigo = Integer.parseInt(tfCodigo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Se esperaba un numero entero en Código", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Producto p = null;
        for (Producto producto : listaProductos.getProductos()) {
            if (producto.getCodigo() == codigo) {
                p = producto;
            }
        }

        if (p != null && !listaProductos.quitar(p)) {
            JOptionPane.showMessageDialog(this, "No se ha encontrado ningún objeto con este código", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        String codigoString = tfCodigo.getText();
        String descripcion = tfDescripcion.getText();
        String precioStr = tfPrecio.getText();
        String rubro = (String) cbRubro.getSelectedItem();
        String existenciasStr = tfExistencias.getText();

        if (codigoString.isBlank() || descripcion.isBlank()
                || precioStr.isBlank() || rubro == null
                || existenciasStr.isBlank()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos antes de agregar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int codigo;
        try {
            codigo = Integer.parseInt(codigoString);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Se esperaba un numero entero en Código", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double precio;
        try {
            precio = Double.parseDouble(precioStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Se esperaba un numero en Precio", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int existencias;
        try {
            existencias = Integer.parseInt(existenciasStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Se esperaba un numero entero en Stock", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Producto producto = new Producto(codigo, descripcion, precio, existencias, rubro);
        if (!listaProductos.agregar(producto)) {
            JOptionPane.showMessageDialog(this, "El número de código ya está en uso.\nElija otro", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> cbRubro;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lDescripcion;
    private javax.swing.JLabel lPrecio;
    private javax.swing.JLabel lRubro;
    private javax.swing.JLabel lStock;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfExistencias;
    private javax.swing.JTextField tfPrecio;
    // End of variables declaration//GEN-END:variables
}
